matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      language: python
      python: 3.6.2
    - os: osx
      sudo: required
    - os: windows
      language: python
      sudo: required
      python: 3.6.2
addons:
  chrome: stable
before_script:
  - if [[ "$TRAVIS_OS_NAME" != "osx" ]]; then export DISPLAY=:99.0 ; fi
  - if [[ "$TRAVIS_OS_NAME" != "osx" ]]; then sh -e /etc/init.d/xvfb start ; fi
  - if [[ "$TRAVIS_OS_NAME" != "osx" ]]; then sleep 3  ; fi
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install python3 ; fi
  - python3 -V
  - pip3 -V
# command to install dependencies
install:
  - pip3 install -r requirements.txt
# command to run tests
script:
  - sudo chmod +x jadx/bin/jadx
  - python3 main.py test-apk.apk # or py.test for Python versions 3.5 and below
  # Building the executable for the deployment
  - pip3 install pyinstaller
  - python3 -m PyInstaller main.py --onefile --add-data jadx:jadx -p jadx --icon icon.ico --name stacoan --clean --noupx
  - mkdir deploy
  - cp dist/* ./deploy/
  - mkdir ./deploy/html
  - cp -R report/html ./deploy/html
  - mkdir ./deploy/jadx
  - cp -R jadx ./deploy/jadx
  - cp -R config ./deploy/config
  - cp README.md ./deploy/README.md
  - cp config.ini ./deploy/config.ini
  - name_zip=$TRAVIS_OS_NAME+".zip"
  - zip -r $(echo $name_zip) deploy

deploy:
  provider: releases
  skip_cleanup: true
  prerelease: true
  body: "This is an automated build."
  tag_name: "v0.2 $(date +'%Y%m%d%H%M%S')"
  on:
    tags: true
  api_key:
    secure: LHo4mTW5GAq2YqArglFcB4T4Gmq8Z3aZIZiAGtvtdUhHhtKBJR1LDRITDsedeNXHf/wye9IxBwbiA6E1GDeZzsk20i6+5UMxsMasMYlq4OFVrbJrdm6adrjagSgZp7JePbk2EXzFFYDL4lvXT3lhSXW7exKBhzQRcr3y4Tuc2DczJ7G5y+ZQnrUYOLX3ln5Pq2DViUcPmH+ycFAq89X5zrXKyIoZTNAA3ffqVac0gMX24sLodTU/bMnp22fde6v7W//yx4nkoaaVqRk3doE8wxm1oaBaAT+Oy9N4P5AZ/5HA3mb96o0+Rfo3FIZGJ9kvv1Mk1eVb8ii1Kd0hA6EzU+ay9w84p77oSPUCAWUcJgNYgcsurRnW9f4GjRWt2KQ8NWP9sHOTsabtkLVhJ6/RBdSM5cvZkxMUgP8ebOtIyaWouO3qBYcZ43Jio44IhF/a6pRIlhLsRuozaBvOWfN/207d2I2p+EMcwpK9I14A1wbc+7Naph6a7gACohmt9+6r8GTMzLPwhev1T7JJn3DbPLsQBX4yWaMMbdITDgbZUxTluwYviCehrb7WhtfMiNWeSluCvn2p9rwyxxUq2fgxd3gteeEVYdTjLa3rTunRS8F8X/YDhgRmd9TEoB0OAkW+vqOAFaPED6tvhVlLHxIotHQ4rQt2LtBD/TaGnbnJiJ4=
  file: $(echo $name_zip)
  on:
    repo: vincentcox/StaCoAn
    
