sudo: required
dist: trusty
language: python
python:
  - 3.6.2
addons:
  chrome: stable
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
before_install:
  - sudo apt-get -y install python3-pip python-dev
  - python3 -V
  - pip3 -V
# command to install dependencies
install:
  - pip3 install -r requirements.txt
# command to run tests
script:
  - sudo chmod +x jadx/bin/jadx
  - python3 main.py test-apk.apk # or py.test for Python versions 3.5 and below
